language: node_js
node_js:
  - "8.11"

sudo: false

os:
  - osx
  - linux

env:
  - NODE_ENV="test"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - npm i -g npm@5.8.0

install:
  - npm ci
  - npm run vscode:prepublish

script:
  - npm test